"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
from django.conf.global_settings import LOGIN_REDIRECT_URL, LOGOUT_REDIRECT_URL

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['scruz.pythonanywhere.com', 'localhost', '127.0.0.1', 'timid-humiliate-blissful.ngrok-free.dev', 'timid-humiliate-blissful.ngrok-free.app']

CSRF_TRUSTED_ORIGINS = ['https://timid-humiliate-blissful.ngrok-free.dev', 'https://timid-humiliate-blissful.ngrok-free.app']

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'gestion',
    'webhook',
    'notificaciones',
    'public',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'gestion.context_processors.notificaciones',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Auth — Opción A (Django built-in auth), ver Handoff Frontend — Sistema de Autenticación
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'gestion:dashboard'
LOGOUT_REDIRECT_URL = '/'

# Unfold config

UNFOLD = {
    'SITE_TITLE': 'App Mudanzas',
    'SITE_HEADER': 'Gestión de mudanzas',
    'SITE_SUBHEADER': 'Panel de administración',

    "SIDEBAR": {
        "navigation": [
            {
                "title": "Operaciones",
                "items": [
                    {
                        "title": "Mudanzas",
                        "icon": "local_shipping",
                        "link": "/admin/gestion/mudanza/",
                    },
                    {
                        "title": "Clientes",
                        "icon": "people",
                        "link": "/admin/gestion/cliente/",
                    },
                ],
            },
            {
                "title": "Flota y Personal",
                "items": [
                    {
                        "title": "Camiones",
                        "icon": "fire_truck",
                        "link": "/admin/gestion/camion/",
                    },
                    {
                        "title": "Empleados",
                        "icon": "badge",
                        "link": "/admin/gestion/empleado/",
                    },
                ],
            },
            {
                "title": "Configuración",
                "items": [
                    {
                        "title": "Tarifas",
                        "icon": "payments",
                        "link": "/admin/gestion/tarifabase/",
                    },
                ],
            },
        ],
    },
}

# Celery config

CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = config("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "America/Argentina/Buenos_Aires"
CELERY_TASK_TRACK_STARTED = True

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'recordatorio-24h-mudanzas': {
        'task': 'notificaciones.task.enviar_recordatorio_24h_pendientes',
        'schedule': crontab(minute='*/15'),
    }
}

# Chatbot
CHATBOT_NOMBRE_EMPRESA = "Tu Empresa de Mudanzas"
CHATBOT_NOMBRE_BOT = "Movi"  # nombre del asistente virtual
CHATBOT_URL_FORMULARIO = "https://scruz.pythonanywhere.com/presupuesto/"
CHATBOT_URL_WEB_PRINCIPAL = "https://scruz.pythonanywhere.com/"

# Twilio / Whatsapp
TWILIO_ACCOUNT_SID   = config("TWILIO_ACCOUNT_SID",   default="")
TWILIO_AUTH_TOKEN    = config("TWILIO_AUTH_TOKEN",     default="")
TWILIO_WHATSAPP_FROM = config("TWILIO_WHATSAPP_FROM",  default="")
TWILIO_SANDBOX = False
# URL pública de este servidor, usada para validar la firma de Twilio.
# Debe coincidir exactamente con la URL configurada en el Twilio Console.
SITE_BASE_URL = config("SITE_BASE_URL", default="")

#MP
MERCADOPAGO_ACCESS_TOKEN = config('MERCADOPAGO_ACCESS_TOKEN')
MERCADOPAGO_SANDBOX = config('MERCADOPAGO_SANDBOX')

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_ENGINE = config('DB_ENGINE', default='sqlite')

if DB_ENGINE == 'postgres':

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config("DB_NAME"),
            "USER": config("DB_USER"),
            "PASSWORD": config("DB_PASSWORD"),
            "HOST": config("DB_HOST", default="localhost"),
            "PORT": config("DB_PORT", default="5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
            "OPTIONS": {
                'timeout': 20,
            }
        }
    }

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_URL = '/accounts/login'
LOGIN_REDIRECT_URL = '/gestion'
LOGOUT_REDIRECT_URL = '/'

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

